---
title: "The Impact on Job Interest of Beginner Programmers"
subtitle: "TBD"
author: "TBD"
thanks: "https://github.com/bonjwow/new-coders"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
output:
  bookdown::pdf_document2:
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(stargazer)
library(psych)
# install.packages("PerformanceAnalytics")
library(PerformanceAnalytics)
# install.packages("QuantPsyc")
library(QuantPsyc)
library(car)
```

# Introduction




# Data
```{r, include=FALSE}
#### TODO's ####
# Explain raw data 
#
```

```{r}
#### Message ####
# Show code for reviewers
#
# // Variables
# Y: MoneyForLearning
# X: Age, CityPopulation, CommuteTime, Income, MonthsProgramming, SchoolDegree
# c: Gender
# 
# // Clean csv
# https://github.com/bonjwow/new-coders/blob/main/inputs/data/clean_new-coders.csv
#
#

#### Get data ####
dfNewCoders <- 
  readr::read_csv("../../inputs/data/clean_new-coders.csv")

```


```{r}
#### Descriptive statistics ####
stargazer::stargazer(data.frame(dfNewCoders), type="text")

```

```{r}
#### Correlation analysis ####

### Print correlation coefficient
round(cor(dfNewCoders), 3)

```


```{r}
### Print correlation matrix
PerformanceAnalytics::chart.Correlation(dfNewCoders, 
                                        histogram = TRUE, 
                                        pch = 19)
```


# Model
```{r, include=FALSE}
#### TODO's ####
# Write out what each variable is
# Weaknesses and next steps
```


```{r}
#### Multiple regression analysis ####
summary(fit.lm <- lm(formula = 
                       MoneyForLearning ~ 
                       Gender +
                       CityPopulation +
                       CommuteTime +
                       Income +
                       MonthsProgramming +
                       SchoolDegree, 
                     data = dfNewCoders))
```
```{r}
#### Beta ####
QuantPsyc::lm.beta(fit.lm)
```



```{r}
#### Check multicollinearity with Variance Inflation Factor (VIF) & Tolerance ####

### VIF
car::vif(fit.lm)
### Tolerance
1/car::vif(fit.lm)
```

```{r}

```



# Results

# Discussion
```{r, include=FALSE}
#### TODO's ####
# Write at least 2.5 pages for the Discussion section
# Weaknesses and next steps
```


\newpage

# Appendix {-}

\newpage


# References


